import IsNotAuth from "../_protectedRoutes/isNotAuth";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <IsNotAuth>{children}</IsNotAuth>;
}
