import IsNotAuth from "../_components/IsNotAuth";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return;
  <IsNotAuth>{children}</IsNotAuth>;
}
