export const campaigns = [
  {
    pictureUrl:
      "https://images.unsplash.com/photo-1593069567131-53a0614dde1d?q=80&w=426&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    additionalPhotos: [],
    title: "Projeto Floresta Viva",
    description:
      "O Projeto Floresta Viva visa a conservação e restauração de áreas florestais degradadas na região amazônica. Por meio do reflorestamento e da educação ambiental, buscamos promover a biodiversidade, mitigar as mudanças climáticas e gerar oportunidades econômicas sustentáveis para comunidades locais.",
    createdIn: "2023-06-15",
    owner: "Associação Amigos da Floresta",
    isAd: true,
    isLiked: false,
    isOwnerVerified: true,
    type: "Conservação Ambiental",
    affectedRegion: "Região Amazônica",
    supporters: 5000,
    goal: 1000000,
    raised: 250000,
  },
  {
    pictureUrl:
      "https://images.unsplash.com/photo-1538300342682-cf57afb97285?q=80&w=426&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    additionalPhotos: [],
    title: "Água Limpa para Todos",
    description:
      "O projeto visa fornecer acesso à água potável em comunidades rurais do semiárido brasileiro. Utilizaremos tecnologias de captação de água da chuva e sistemas de filtragem para garantir água limpa e segura para consumo humano e agrícola.",
    createdIn: "2022-09-20",
    owner: "Associação Água Limpa",
    isAd: true,
    isLiked: true,
    isOwnerVerified: true,
    type: "Acesso à Água",
    affectedRegion: "Semiárido Brasileiro",
    supporters: 10000,
    goal: 500000,
    raised: 300000,
  },
  {
    pictureUrl:
      "https://images.unsplash.com/photo-1604187351574-c75ca79f5807?q=80w=426&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    additionalPhotos: [],
    title: "Reciclando Vidas",
    description:
      "Iniciativa que promove a coleta seletiva e a reciclagem de resíduos sólidos em áreas urbanas. Além de reduzir a poluição ambiental, oferecemos oportunidades de emprego para catadores de materiais recicláveis e conscientização sobre a importância da preservação do meio ambiente.",
    createdIn: "2023-04-10",
    owner: "Cooperativa ReciclaMais",
    isAd: true,
    isLiked: false,
    isOwnerVerified: true,
    type: "Reciclagem",
    affectedRegion: "Áreas Urbanas",
    supporters: 7000,
    goal: 200000,
    raised: 100000,
  },
  {
    pictureUrl:
      "https://images.unsplash.com/photo-1532509774891-141d37f25ae9?q=80&w=426&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    additionalPhotos: [],
    title: "Sementes da Esperança",
    description:
      "Promovemos o cultivo agroecológico em comunidades rurais desfavorecidas. Oferecemos capacitação em práticas agrícolas sustentáveis, distribuição de sementes orgânicas e apoio técnico para garantir a segurança alimentar e gerar renda para famílias locais.",
    createdIn: "2023-01-05",
    owner: "Instituto Terra Fértil",
    isAd: false,
    isLiked: true,
    isOwnerVerified: true,
    type: "Agricultura Sustentável",
    affectedRegion: "Comunidades Rurais",
    supporters: 4000,
    goal: 150000,
    raised: 75000,
  },
  {
    pictureUrl:
      "https://images.unsplash.com/photo-1581242163695-19d0acfd486f?q=80&w=426&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    additionalPhotos: [],
    title: "Preservando Nossos Mares",
    description:
      "Iniciativa para a conservação dos ecossistemas marinhos e a proteção da biodiversidade costeira. Realizamos a limpeza de praias, monitoramento de espécies marinhas e campanhas de conscientização sobre a poluição marinha.",
    createdIn: "2022-11-30",
    owner: "ONG Mar Vivo",
    isAd: true,
    isLiked: true,
    isOwnerVerified: true,
    type: "Conservação Marinha",
    affectedRegion: "Zonas Costeiras",
    supporters: 6000,
    goal: 250000,
    raised: 180000,
  },
  {
    pictureUrl:
      "https://images.unsplash.com/photo-1521618755572-156ae0cdd74d?q=80&w=426&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    additionalPhotos: [],
    title: "Energia Solar nas Escolas",
    description:
      "Implantamos sistemas de energia solar em escolas públicas, reduzindo custos de eletricidade e promovendo a educação ambiental. Além disso, capacitamos professores e alunos para a gestão sustentável da energia.",
    createdIn: "2023-02-15",
    owner: "Associação Sol Sustentável",
    isAd: false,
    isLiked: false,
    isOwnerVerified: true,
    type: "Energia Renovável",
    affectedRegion: "Escolas Públicas",
    supporters: 3000,
    goal: 100000,
    raised: 60000,
  },
  {
    pictureUrl:
      "https://images.unsplash.com/photo-1569227997603-33b9f12af927?q=80&w=426&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    additionalPhotos: [],
    title: "Ar Puro para Respirar",
    description:
      "Campanha de reflorestamento urbano para combater a poluição do ar e melhorar a qualidade de vida em áreas urbanas. Plantamos árvores nativas, promovemos a conscientização ambiental e incentivamos a participação da comunidade.",
    createdIn: "2023-07-20",
    owner: "Movimento Verde Vivo",
    isAd: true,
    isLiked: true,
    isOwnerVerified: true,
    type: "Reflorestamento Urbano",
    affectedRegion: "Áreas Urbanas",
    supporters: 5500,
    goal: 180000,
    raised: 120000,
  },
  {
    pictureUrl:
      "https://images.unsplash.com/photo-1473594659356-a404044aa2c2?q=80&w=426&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    additionalPhotos: [],
    title: "Cultivando o Futuro",
    description:
      "Iniciativa que promove a agricultura familiar sustentável em comunidades rurais. Oferecemos treinamento em técnicas agroecológicas, acesso a mercados justos e apoio para a comercialização de produtos orgânicos.",
    createdIn: "2022-12-10",
    owner: "Cooperativa Agricultura Sustentável",
    isAd: true,
    isLiked: true,
    isOwnerVerified: true,
    type: "Agricultura Familiar",
    affectedRegion: "Comunidades Rurais",
    supporters: 4800,
    goal: 200000,
    raised: 90000,
  },
  {
    pictureUrl:
      "https://images.unsplash.com/photo-1586400792375-d6b8f82db2e6?q=80&w=426&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    additionalPhotos: [],
    title: "Guardiões das Florestas",
    description:
      "Programa de voluntariado ambiental que visa a proteção e monitoramento de áreas de conservação florestal. Realizamos patrulhas para prevenir desmatamento ilegal, combater incêndios florestais e promover a educação ambiental.",
    createdIn: "2023-03-05",
    owner: "ONG Verdejando",
    isAd: false,
    isLiked: false,
    isOwnerVerified: true,
    type: "Preservação Florestal",
    affectedRegion: "Áreas de Conservação",
    supporters: 2500,
    goal: 120000,
    raised: 70000,
  },
  {
    pictureUrl:
      "https://images.unsplash.com/photo-1535978115060-d01ae6702684?q=80&w=426&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    additionalPhotos: [],
    title: "Conexão Natureza",
    description:
      "Iniciativa que promove o turismo sustentável em áreas naturais protegidas. Desenvolvemos trilhas ecológicas, estruturas de hospedagem sustentável e programas de educação ambiental para visitantes.",
    createdIn: "2023-08-10",
    owner: "Associação EcoTurismo",
    isAd: true,
    isLiked: true,
    isOwnerVerified: true,
    type: "Turismo Sustentável",
    affectedRegion: "Áreas Naturais Protegidas",
    supporters: 3800,
    goal: 150000,
    raised: 110000,
  },
];
